name: "Setup build environment"
description: "Setup python, ninja-build etc."

# Make top-level permissions on GITHUB_TOKEN more restrictive
permissions:
  contents: read

runs:
  using: "composite"

  steps:
    - name: Set up Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: '3.11'

    - name: Install prerequisites (Linux)
      run: sudo apt-get install --yes ninja-build ccache
      shell: bash

    - name: Install prerequisites (macOS)
      if: ${{ runner.os == 'macOS' }}
      run: brew install ccache ninja
      shell: bash

    - name: Install prerequisites (Windows)
      if: ${{ runner.os == 'Windows' }}
      run: |
        pip install ninja
        choco install ccache --yes
      shell: bash

    - name: Configure ccache
      if: ${{ inputs.cache-enabled == 'true' }}
      run: |
        rm -rf ${{ github.workspace }}/.ccache
        mkdir -p ${{ github.workspace }}/.ccache
        ccache --set-config "cache_dir=${{ github.workspace }}/.ccache"
        ccache --set-config "compression=true"
        ccache --set-config "max_size=300M"
        ccache --zero-stats
      shell: bash

    - name: Enable ccache
      if: ${{ inputs.cache-enabled == 'true' }}
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: ${{ github.workspace }}/.ccache
        key: ${{ runner.os }}-${{ inputs.cache-suffix }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.cache-suffix }}-
          ${{ runner.os }}-
